#!/usr/bin/env python3
"""
gen_palette_lut.py: Generates a lookup table mapping Doom's 256-color palette
to Pebble Time 2's native 64-color RGB222 display format (0b11RRGGBB).
"""

import struct
import sys
import os

def rgb_to_pebble(r, g, b):
    """
    Finds the closest Pebble 64-color RGB222 byte for an 8-bit (r, g, b) triple.
    Each channel in RGB222 has levels [0, 85, 170, 255].
    Pebble byte format: 0b11RRGGBB (Alpha is always 11).
    """
    levels = [0, 85, 170, 255]
    best_dist = float('inf')
    best_code = 0b11000000

    # Weighted Euclidean distance (human perception weights: 0.299 R, 0.587 G, 0.114 B)
    for ri, rv in enumerate(levels):
        for gi, gv in enumerate(levels):
            for bi, bv in enumerate(levels):
                dist = 0.299 * (r - rv)**2 + 0.587 * (g - gv)**2 + 0.114 * (b - bv)**2
                if dist < best_dist:
                    best_dist = dist
                    best_code = 0b11000000 | (ri << 4) | (gi << 2) | bi

    return best_code

def main():
    doom_wad = sys.argv[1] if len(sys.argv) > 1 else "../genesis-DOOM64KB/scripts/doom64.wad"
    out_header = sys.argv[2] if len(sys.argv) > 2 else "../src/pebble/pebble_pal.h"

    if not os.path.exists(doom_wad):
        print(f"Error: WAD not found at {doom_wad}", file=sys.stderr)
        sys.exit(1)

    with open(doom_wad, "rb") as f:
        data = f.read()

    # Find PLAYPAL lump
    numlumps = struct.unpack_from(">h" if struct.unpack_from(">h", data, 4)[0] > 0 else "<h", data, 4)[0]
    is_be = struct.unpack_from(">i", data, 8)[0] < len(data)
    infoofs = struct.unpack_from(">i" if is_be else "<i", data, 8)[0]

    playpal_bytes = None
    for i in range(abs(numlumps)):
        o = infoofs + i * 16
        fp = struct.unpack_from(">i" if is_be else "<i", data, o)[0]
        sz = struct.unpack_from(">H" if is_be else "<H", data, o + 4)[0]
        name = data[o+8:o+16].split(b"\x00")[0].decode("latin1", errors="replace")
        if name == "PLAYPAL":
            playpal_bytes = data[fp:fp + 768] # First palette of 256 RGB triplets
            break

    if not playpal_bytes or len(playpal_bytes) < 768:
        print("Error: Could not locate 768-byte PLAYPAL lump in WAD", file=sys.stderr)
        sys.exit(1)

    lut = []
    for i in range(256):
        r = playpal_bytes[i * 3 + 0]
        g = playpal_bytes[i * 3 + 1]
        b = playpal_bytes[i * 3 + 2]
        p_byte = rgb_to_pebble(r, g, b)
        lut.append(p_byte)

    os.makedirs(os.path.dirname(os.path.abspath(out_header)), exist_ok=True)
    with open(out_header, "w") as f:
        f.write("/* Auto-generated by gen_palette_lut.py */\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write("// Maps Doom palette index (0..255) to Pebble RGB222 (0b11RRGGBB)\n")
        f.write("static const uint8_t doom_to_pebble_pal[256] = {\n")
        for i in range(0, 256, 16):
            chunk = lut[i:i+16]
            f.write("    " + ", ".join(f"0x{x:02x}" for x in chunk) + ",\n")
        f.write("};\n")

    print(f"Generated {out_header} with 256 mapped colors.")

if __name__ == "__main__":
    main()
